name: path-filter
on:
  push: # push event
    paths: # path filter 사용 : path에 변경사항이 생길 떄, 워크플로우가 트리거
      - ".github/workflows/part1/*" # .github/workflow/part1/ 내 모든 파일이 변경 될 때, 동작하는 Workflow
      - "!.github/workflows/part1/push.yaml" # 해당 디렉토리내 push.yaml은 제외 (특정 파일 또는 디렉토리를 워크플로우 트리거에서 제외하는 기호 : !)

jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
      - name: echo hello
        run: echo hello
