name: checkout
on: workflow_dispatch

jobs:
  no-checkout: # checkout 미사용
    runs-on: ubuntu-latest
    steps:
      - name: check file list
        run: cat README.md

  checkout: # checkout 사용
    runs-on: ubuntu-latest
    steps:
      - name: use checkout action
        uses: actions/checkout@v4
      - name: check file list
        run: cat README.md
