name: if-2
on: push

jobs:
  jobs:
    runs-on: ubuntu-latest
    steps:
      - name: exit 1
        run: exit 1
      - name: echo
        run: echo hello

  job2:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo hello
