name: matrix
on: push

jobs:
  get-matrix:
    strategy:
      os: [windows-latest, ubuntu-latest]
      version: [12, 14]
    runs-on: ${{ matrix.os }}
    steps:
      - name: check matrix
        run: |
          echo ${{ matrix.os }}
          echo ${{ matrix.version }}
