name: timeout
on: push

jobs:
  timeout:
    runs-on: ubuntu-latest
    timeout-minutes: 2 # 해당 타임아웃 값으로 인해 무한 루프만 2분간 실행되다가 종료
    steps:
      - name: loop
        run: | # 1초에 카운트가 1씩 올라가는 무한 루프 Step 스크립트
          count=0
          while true; do
            echo "seconds: $count"
            count=$((count+1))
            sleep 1
          done

      - name: echo # echo hello 출력 (두 번쨰 실행은 실행되지 않음)
        run: echo hello
