name: workflow-dispatch
on:
  workflow-dispatch:
    # input 작업
    inputs:
      name:
        description: "set name"
        required: true
        default: "github-actions"
        type: string

      environment:
        description: "set env"
        required: true
        default: "dev"
        type: choice
        options: # choice 데이터 타입을 사용하려면, options라는 키워드를 사용해 사용자가 고를 수 있도록 설정
          - dev
          - qa
          - prod # 옵션 지정

  # job 작업
  jobs:
    workflow-dispatch-job:
      runs-on: ubuntu-latest # job을 실행시킬 runner 지정
      steps: # 실행할 step 지정하는 step 집합
        - name: step1 # 실행시킬 step 이름 지정 (각 step 마다 명시적 지정 또는 생략 가능)
          run: echo hello world # 이 워크플로우는 push 이벤트 발생 시, 트리거가 되어 push job이라는 이름의 job 한 개가 실행되고, 이를 출력하고 종료
        - name: step2
          run: | # | : 멀티라인 커맨드
            echo hello world
            echo github action
        - name: echo inputs
          run: |
            echo ${{ inputs.name }}
            echo ${{ inputs.environment }}
